name: V3 manual Windows build and test

on:
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  Windows:
    uses: ./.github/workflows/windows.yml
    with:
      image: "2022"
      tests: false
